// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_generated

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int32
	AppID     int32
	Key       string
	CreatedAt pgtype.Timestamp
	LastUsed  pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type App struct {
	ID              int32
	CreatedByUserID pgtype.UUID
	Name            string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	DeletedAt       pgtype.Timestamp
}

type KeyValue struct {
	AppID     int32
	Key       string
	Value     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
